github: [] # Kein GitHub Sponsors aktiv
patreon: 
open_collective: 
ko_fi: 
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
lfx_crowdfunding: 
polar: 
buy_me_a_coffee: 
thanks_dev: 
custom: ['https://paypal.me/technorevival', 'https://thc-legacy-rp.de/']
